### ISSUE TITLE
Windows build failed

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cudatoolkit-feedstock#1]
Looks like the Windows build [failed on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=225204&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802 ). Have [attached the log]( https://github.com/conda-forge/cudatoolkit-feedstock/files/5380061/cudatoolkit_win_64_20201014_1.txt ) as well. Seems NvToolsExt path could not be found (snippet of failure below):

```python
NvToolsExt path: None
Traceback (most recent call last):
  File "D:\bld\cudatoolkit_1602697864220\work\build.py", line 408, in <module>
    main()
  File "D:\bld\cudatoolkit_1602697864220\work\build.py", line 404, in main
    extractor.extract()
  File "D:\bld\cudatoolkit_1602697864220\work\build.py", line 281, in extract
    self.copy(store)
  File "D:\bld\cudatoolkit_1602697864220\work\build.py", line 219, in copy
    self.copy_files(cuda_lib_dir=store, nvvm_lib_dir=store, libdevice_lib_dir=store)
  File "D:\bld\cudatoolkit_1602697864220\work\build.py", line 166, in copy_files
    filepaths += self.get_paths(
  File "D:\bld\cudatoolkit_1602697864220\work\build.py", line 131, in get_paths
    raise RuntimeError(msg)
RuntimeError: Cannot find item: nvToolsExt, looked for nvToolsExt64_1.dll
```

**Comment by scopatz** [comment]
Yeah this is because we need to install the NVIDIA drivers on Windows. I think the easiest way is to install them via `choco` as per  https://chocolatey.org/packages/nvidia-display-driver, this should likely be change in conda-smithy.

**Comment by jakirkham** [comment]
Ah ok. I thought it passed in `staged-recipes` for some reason. Maybe I wasn't reading that correctly.

cc @kkraus14 (in case you have any thoughts here 🙂)

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/7 )
