### ISSUE TITLE
Builds for `linux_64`'s `cudatoolkit` version `11.8.0` package fail (out of space on CI)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cudatoolkit-feedstock#91]
The `linux_64`'s `cudatoolkit` version `11.8.0` package builds [fail on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=741663&view=logs&j=b7a895b1-8909-5023-4a22-40a4698fe576&t=97202c64-61a6-5e06-026a-f8da320182b5&l=724 ) (also have [attached the log]( https://github.com/conda-forge/cudatoolkit-feedstock/files/11985963/linux_64_major_minor_ver11.8.0.txt ) for posterity) due to lack of space:

````
Extract command: $SRC_DIR/cuda_11.8.0_520.61.05_linux.run --silent --override --nox11 --toolkit --installpath=/tmp/tmpykdzl9n7
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::copy_file: No space left on device: "./builds/nsight_systems/documentation/pdf/Archives.pdf", "/tmp/tmpykdzl9n7/nsight-systems-2022.4.2/documentation/pdf/Archives.pdf"
/home/conda/feedstock_root/build_artifacts/cudatoolkit_1688762207981/work/cuda_11.8.0_520.61.05_linux.run: line 524:   725 Aborted                 (core dumped) ./cuda-installer --silent --override --toolkit --installpath=/tmp/tmpykdzl9n7
C
```

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by RaulPPelaez** [comment]
I started to run out of space for CUDA 11.8 in several feedstocks. CUDA 12 and 11.2 do not suffer from this.
https://github.com/conda-forge/torchmd-net-feedstock/pull/21/
https://github.com/conda-forge/torchani-feedstock/pull/32
For TorchMD-Net the requirements are as follow:
```yaml
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
    - cuda-version =={{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')]
  host:
    - python
    - pip
    - libtorch
    - pytorch =*={{ torch_proc_type }}*
    - cuda-version =={{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')]
```
```shell
2024-02-21T07:10:25.2853989Z ## Package Plan ##
2024-02-21T07:10:25.2854547Z 
2024-02-21T07:10:25.2864927Z   environment location: /home/conda/feedstock_root/build_artifacts/torchmd-net_1708499262101/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
2024-02-21T07:10:25.2877177Z 
2024-02-21T07:10:25.2877294Z 
2024-02-21T07:10:25.2877815Z The following NEW packages will be INSTALLED:
2024-02-21T07:10:25.2877952Z 
2024-02-21T07:10:25.2878334Z     _libgcc_mutex:     0.1-conda_forge                 conda-forge
2024-02-21T07:10:25.2878660Z     _openmp_mutex:     4.5-2_kmp_llvm                  conda-forge
2024-02-21T07:10:25.2878993Z     bzip2:             1.0.8-hd590300_5                conda-forge
2024-02-21T07:10:25.2879313Z     ca-certificates:   2024.2.2-hbcca054_0             conda-forge
2024-02-21T07:10:25.2879657Z     cuda-version:      11.8-h70ddcb2_2                 conda-forge
2024-02-21T07:10:25.2879976Z     cudatoolkit:       11.8.0-h4ba93d1_13              conda-forge
2024-02-21T07:10:25.2880311Z     cudnn:             8.8.0.121-hcdd5f01_4            conda-forge
2024-02-21T07:10:25.2880641Z     filelock:          3.13.1-pyhd8ed1ab_0             conda-forge
2024-02-21T07:10:25.2880959Z     fsspec:            2024.2.0-pyhca7485f_0           conda-forge
2024-02-21T07:10:25.2881290Z     gmp:               6.3.0-h59595ed_0                conda-forge
2024-02-21T07:10:25.2881609Z     gmpy2:             2.1.2-py311h6a5fa03_1           conda-forge
2024-02-21T07:10:25.2881933Z     icu:               73.2-h59595ed_0                 conda-forge
2024-02-21T07:10:25.2882251Z     jinja2:            3.1.3-pyhd8ed1ab_0              conda-forge
2024-02-21T07:10:25.2882568Z     ld_impl_linux-64:  2.40-h41732ed_0                 conda-forge
2024-02-21T07:10:25.2882911Z     libabseil:         20230802.1-cxx17_h59595ed_0     conda-forge
2024-02-21T07:10:25.2883240Z     libblas:           3.9.0-21_linux64_openblas       conda-forge
2024-02-21T07:10:25.2883583Z     libcblas:          3.9.0-21_linux64_openblas       conda-forge
2024-02-21T07:10:25.2883898Z     libexpat:          2.5.0-hcb278e6_1                conda-forge
2024-02-21T07:10:25.2884221Z     libffi:            3.4.2-h7f98852_5                conda-forge
2024-02-21T07:10:25.2884540Z     libgcc-ng:         13.2.0-h807b86a_5               conda-forge
2024-02-21T07:10:25.2884860Z     libgfortran-ng:    13.2.0-h69a702a_5               conda-forge
2024-02-21T07:10:25.2885198Z     libgfortran5:      13.2.0-ha4646dd_5               conda-forge
2024-02-21T07:10:25.2885523Z     libhwloc:          2.9.3-default_h554bfaf_1009     conda-forge
2024-02-21T07:10:25.2885859Z     libiconv:          1.17-hd590300_2                 conda-forge
2024-02-21T07:10:25.2886176Z     liblapack:         3.9.0-21_linux64_openblas       conda-forge
2024-02-21T07:10:25.2886508Z     libmagma:          2.7.2-h09b5827_2                conda-forge
2024-02-21T07:10:25.2886837Z     libmagma_sparse:   2.7.2-h09b5827_2                conda-forge
2024-02-21T07:10:25.2887148Z     libnsl:            2.0.1-hd590300_0                conda-forge
2024-02-21T07:10:25.2887481Z     libopenblas:       0.3.26-pthreads_h413a1c8_0      conda-forge
2024-02-21T07:10:25.2887803Z     libprotobuf:       4.25.1-hf27288f_2               conda-forge
2024-02-21T07:10:25.2888133Z     libsqlite:         3.45.1-h2797004_0               conda-forge
2024-02-21T07:10:25.2888450Z     libstdcxx-ng:      13.2.0-h7e041cc_5               conda-forge
2024-02-21T07:10:25.2888914Z     libtorch:          2.1.2-cuda118_h12fe058_301      conda-forge
2024-02-21T07:10:25.2889249Z     libuuid:           2.38.1-h0b41bf4_0               conda-forge
2024-02-21T07:10:25.2889557Z     libuv:             1.47.0-hd590300_0               conda-forge
2024-02-21T07:10:25.2889898Z     libxcrypt:         4.4.36-hd590300_1               conda-forge
2024-02-21T07:10:25.2890213Z     libxml2:           2.12.5-h232c23b_0               conda-forge
2024-02-21T07:10:25.2890539Z     libzlib:           1.2.13-hd590300_5               conda-forge
2024-02-21T07:10:25.2890849Z     llvm-openmp:       17.0.6-h4dfa4b3_0               conda-forge
2024-02-21T07:10:25.2891178Z     magma:             2.7.2-h4aca40b_2                conda-forge
2024-02-21T07:10:25.2891507Z     markupsafe:        2.1.5-py311h459d7ec_0           conda-forge
2024-02-21T07:10:25.2891827Z     mkl:               2023.2.0-h84fe81f_50496         conda-forge
2024-02-21T07:10:25.2892232Z     mpc:               1.3.1-hfe3b2da_0                conda-forge
2024-02-21T07:10:25.2892535Z     mpfr:              4.2.1-h9458935_0                conda-forge
2024-02-21T07:10:25.2892855Z     mpmath:            1.3.0-pyhd8ed1ab_0              conda-forge
2024-02-21T07:10:25.2893164Z     nccl:              2.20.3.1-h6103f9b_0             conda-forge
2024-02-21T07:10:25.2893484Z     ncurses:           6.4-h59595ed_2                  conda-forge
2024-02-21T07:10:25.2893804Z     networkx:          3.2.1-pyhd8ed1ab_0              conda-forge
2024-02-21T07:10:25.2894120Z     numpy:             1.26.4-py311h64a7726_0          conda-forge
2024-02-21T07:10:25.2894443Z     openssl:           3.2.1-hd590300_0                conda-forge
2024-02-21T07:10:25.2894747Z     pip:               24.0-pyhd8ed1ab_0               conda-forge
2024-02-21T07:10:25.2895077Z     python:            3.11.8-hab00c5b_0_cpython       conda-forge
2024-02-21T07:10:25.2895391Z     python_abi:        3.11-4_cp311                    conda-forge
2024-02-21T07:10:25.2895735Z     pytorch:           2.1.2-cuda118_py311hde743b7_301 conda-forge
2024-02-21T07:10:25.2896071Z     readline:          8.2-h8228510_1                  conda-forge
2024-02-21T07:10:25.2896385Z     setuptools:        69.1.0-pyhd8ed1ab_1             conda-forge
2024-02-21T07:10:25.2896710Z     sleef:             3.5.1-h9b69904_2                conda-forge
2024-02-21T07:10:25.2897021Z     sympy:             1.12-pypyh9d50eac_103           conda-forge
2024-02-21T07:10:25.2897350Z     tbb:               2021.11.0-h00ab1b0_1            conda-forge
2024-02-21T07:10:25.2897664Z     tk:                8.6.13-noxft_h4845f30_101       conda-forge
2024-02-21T07:10:25.2899504Z     typing_extensions: 4.9.0-pyha770c72_0              conda-forge
2024-02-21T07:10:25.2899949Z     tzdata:            2024a-h0c530f3_0                conda-forge
2024-02-21T07:10:25.2900349Z     wheel:             0.42.0-pyhd8ed1ab_0             conda-forge
2024-02-21T07:10:25.2900788Z     xz:                5.2.6-h166bdaf_0                conda-forge
2024-02-21T07:10:25.2901190Z     zstd:              1.5.5-hfc55251_0                conda-forge
2024-02-21T07:10:25.2901409Z 
2024-02-21T07:11:00.2261422Z Preparing transaction: ...working... done
2024-02-21T07:11:04.1219243Z Verifying transaction: ...working... done
2024-02-21T07:11:29.3639030Z Executing transaction: ...working... By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html
2024-02-21T07:11:29.3640550Z 
2024-02-21T07:11:29.7518010Z By downloading and using the cuDNN conda packages, you accept the terms and conditions of the NVIDIA cuDNN EULA -
2024-02-21T07:11:29.7519074Z   https://docs.nvidia.com/deeplearning/cudnn/sla/index.html
2024-02-21T07:11:29.7519340Z 
2024-02-21T07:11:40.3175854Z done
2024-02-21T07:11:40.3436387Z Reloading output folder: /home/conda/feedstock_root/build_artifacts
2024-02-21T07:11:40.6177259Z Reloading output folder: /home/conda/feedstock_root/build_artifacts
2024-02-21T07:11:54.9072857Z 
2024-02-21T07:11:54.9078471Z ## Package Plan ##
2024-02-21T07:11:54.9079094Z 
2024-02-21T07:11:54.9080640Z   environment location: /home/conda/feedstock_root/build_artifacts/torchmd-net_1708499262101/_build_env
2024-02-21T07:11:54.9080845Z 
2024-02-21T07:11:54.9303709Z 
2024-02-21T07:11:54.9304469Z The following NEW packages will be INSTALLED:
2024-02-21T07:11:54.9304663Z 
2024-02-21T07:11:54.9305148Z     _libgcc_mutex:                        0.1-conda_forge     conda-forge
2024-02-21T07:11:54.9305497Z     _openmp_mutex:                        4.5-2_gnu           conda-forge
2024-02-21T07:11:54.9306531Z     _sysroot_linux-64_curr_repodata_hack: 3-h69a702a_14       conda-forge
2024-02-21T07:11:54.9306942Z     binutils_impl_linux-64:               2.40-hf600244_0     conda-forge
2024-02-21T07:11:54.9307277Z     binutils_linux-64:                    2.40-hbdbef99_2     conda-forge
2024-02-21T07:11:54.9315016Z     cuda-version:                         11.8-h70ddcb2_2     conda-forge
2024-02-21T07:11:54.9315402Z     gcc_impl_linux-64:                    11.4.0-h7aa1c59_5   conda-forge
2024-02-21T07:11:54.9315735Z     gcc_linux-64:                         11.4.0-hfd045f2_2   conda-forge
2024-02-21T07:11:54.9316079Z     gxx_impl_linux-64:                    11.4.0-h7aa1c59_5   conda-forge
2024-02-21T07:11:54.9316403Z     gxx_linux-64:                         11.4.0-hfc1ae95_2   conda-forge
2024-02-21T07:11:54.9316752Z     kernel-headers_linux-64:              3.10.0-h4a8ded7_14  conda-forge
2024-02-21T07:11:54.9317100Z     ld_impl_linux-64:                     2.40-h41732ed_0     conda-forge
2024-02-21T07:11:54.9317436Z     libgcc-devel_linux-64:                11.4.0-h922705a_105 conda-forge
2024-02-21T07:11:54.9317775Z     libgcc-ng:                            13.2.0-h807b86a_5   conda-forge
2024-02-21T07:11:54.9318093Z     libgomp:                              13.2.0-h807b86a_5   conda-forge
2024-02-21T07:11:54.9318431Z     libsanitizer:                         11.4.0-h4dcbe23_5   conda-forge
2024-02-21T07:11:54.9319453Z     libstdcxx-devel_linux-64:             11.4.0-h922705a_105 conda-forge
2024-02-21T07:11:54.9319855Z     libstdcxx-ng:                         13.2.0-h7e041cc_5   conda-forge
2024-02-21T07:11:54.9320196Z     nvcc_linux-64:                        11.8-h41dc85b_23    conda-forge
2024-02-21T07:11:54.9320510Z     sed:                                  4.8-he412f7d_0      conda-forge
2024-02-21T07:11:54.9320839Z     sysroot_linux-64:                     2.17-h4a8ded7_14    conda-forge
2024-02-21T07:11:54.9320987Z 
2024-02-21T07:11:55.6954402Z Traceback (most recent call last):
2024-02-21T07:11:55.6955797Z   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
2024-02-21T07:11:55.6956683Z     sys.exit(main())
2024-02-21T07:11:55.6957437Z   File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
2024-02-21T07:11:55.6964241Z     call_conda_build(action, config)
2024-02-21T07:11:55.6966584Z   File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
2024-02-21T07:11:55.6967169Z     result = api.build(
2024-02-21T07:11:55.6967771Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 254, in build
2024-02-21T07:11:55.6972450Z     return build_tree(
2024-02-21T07:11:55.6973174Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3789, in build_tree
2024-02-21T07:11:55.6988947Z     packages_from_this = build(
2024-02-21T07:11:55.6989831Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2573, in build
2024-02-21T07:11:55.6993397Z     create_build_envs(top_level_pkg, notest)
2024-02-21T07:11:55.6994192Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2413, in create_build_envs
2024-02-21T07:11:55.6997683Z     environ.create_env(
2024-02-21T07:11:55.6998486Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1056, in create_env
2024-02-21T07:11:55.7199167Z     execute_actions(actions, index)
2024-02-21T07:11:55.7200428Z   File "/opt/conda/lib/python3.10/site-packages/conda/common/io.py", line 85, in decorated
2024-02-21T07:11:55.7202879Z     return f(*args, **kwds)
2024-02-21T07:11:55.7203839Z   File "/opt/conda/lib/python3.10/site-packages/conda/plan.py", line 343, in execute_actions
2024-02-21T07:11:55.7212797Z     execute_instructions(plan, index, verbose)
2024-02-21T07:11:55.7214023Z   File "/opt/conda/lib/python3.10/site-packages/conda/plan.py", line 606, in execute_instructions
2024-02-21T07:11:55.7214760Z     cmd(state, arg)
2024-02-21T07:11:55.7215415Z   File "/opt/conda/lib/python3.10/site-packages/conda/instructions.py", line 67, in PROGRESSIVEFETCHEXTRACT_CMD
2024-02-21T07:11:55.7220320Z     progressive_fetch_extract.execute()
2024-02-21T07:11:55.7221228Z   File "/opt/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 885, in execute
2024-02-21T07:11:55.7230792Z     raise CondaMultiError(not_cancelled)
2024-02-21T07:11:55.7231738Z conda.CondaMultiError: Error with archive /home/conda/feedstock_root/build_artifacts/pkg_cache/binutils_impl_linux-64-2.40-hf600244_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:
2024-02-21T07:11:55.7232288Z 
2024-02-21T07:11:55.7232642Z failed with error: [Errno 28] No space left on device
2024-02-21T07:11:55.7233152Z Failed to write to /home/conda/feedstock_root/build_artifacts/pkg_cache/libsanitizer-11.4.0-h4dcbe23_5.conda.partial
2024-02-21T07:11:55.7233421Z   errno: 28
2024-02-21T07:11:55.7233788Z Failed to write to /home/conda/feedstock_root/build_artifacts/pkg_cache/libsanitizer-11.4.0-h4dcbe23_5.conda.partial
2024-02-21T07:11:55.7234013Z   errno: 28
2024-02-21T07:11:55.7234092Z 
2024-02-21T07:12:02.6623432Z 
2024-02-21T07:12:02.7617187Z ##[error]Bash exited with code '1'.
2024-02-21T07:12:02.8359998Z ##[section]Finishing: Run docker build
```

**Comment by jakirkham** [comment]
Would try this

https://github.com/conda-forge/cudatoolkit-feedstock/blob/5c632f411a0553d1c1b914bce02a41099e5ce03d/conda-forge.yml#L1-L2

Also need to re-render after

More details in PR: https://github.com/conda-forge/cudatoolkit-feedstock/pull/95
